### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by CvH** [projectM-visualizer/projectm#94] opened 2018-08-10 07:30 UTC
Hi, I try to cross compile but it fails for some error. Strangely it shows no error so I have no idea why it fails.
Happens with 3.0.0 and 3.1.0-beta1 - could someone hint me what goes wrong ?
https://pastebin.com/YbWYp96f

**Comment by revmischa** [comment] 2018-08-10 09:28
That is rather strange... yeah I don't see the error either. How can I help?
`--disable-static --enable-shared` looks weird.. try building static?

**Comment by CvH** [comment] 2018-08-11 07:26
>try building static?

tx for feedback but doesn't fix it https://pastebin.com/urZ1de7N
still the same "error"

**Comment by CvH** [comment] 2018-08-11 07:42
If I use the plain source and not the "release" (even with the same commit) it works.
https://pastebin.com/gtv0iPZj
looks like the release configure is a bit borked?

**Comment by CvH** [comment] 2018-08-14 19:46
> Most of the changes would be here

it is already not compiling at 3.0.0

> Any idea what might affect the cross compiler?

Tbh no idea, we have ~1000 packages the are working okay so I can only guess that the release files from here are doing something "strange". But I guess its not worth to dig into it as long the manual way works
```
./autogen.sh
./configure && make
```
Maybe just something something to remember for the future if someone else have similar problems at an not that exotic build environment :)

**Comment by revmischa** [comment] 2018-08-14 19:48
Alright thanks for the info... will keep eyes peeled

**Comment by deltaoscarmike** [comment] 2018-08-15 19:12
The error is at line 3129 of https://pastebin.com/YbWYp96f

``
make[4]: *** No rule to make target '/libprojectM-3.1.0-beta1/src/libprojectM/MilkdropPresetFactory/libMilkdropPresetFactory.la', needed by 'libprojectM.la'.  Stop.
``

This issue is not due to cross compiling, it's an out of tree building issue, steps to reproduce:
```
tar xzf projectM-3.1.0-beta1.tar.gz 
cd projectM-3.1.0-beta1
mkdir build && cd build
../configure && make -j4
```

The source of this issue is located in Makefile.am files which use the define ${top_srcdir} in their _LIBADD directives. ${top_srcdir} points to source directory thus built files are not accessible.
The fix is to replace ${top_srcdir} with relative paths in _LIBADD directives.

**Comment by deltaoscarmike** [comment] 2018-08-23 20:05
Issue is fixed, closing it

**Closed by deltaoscarmike** 2018-08-23 20:05 UTC
