### ISSUE TITLE
[APP BUG] Steam app refusing to install on Linux

### ISSUE THREAD

**Issue by ufgkirk** [projectM-visualizer/projectm#838] opened 2024-08-18 16:14 UTC
### Please confirm the following points:

- [X] This report is NOT about the Android apps in the Play Store
- [X] I have [searched the project page](https://github.com/search?q=org%3AprojectM-visualizer+type%3Aissue+&type=issues) to check if the issue was already reported

### Affected Application

projectM Standalone SDL2 Frontend (includes the Steam app)

### Operating System

Linux (Desktop)

### Additional Application Details

I am running Debian 12 with the KDE Plasma desktop interface.  When I began this process, I had Steam installed from the Flatpak.  Due to some conflicting information online about Flatpak file permissions, I decided to go ahead and uninstall that instance of Steam and reinstall it from the Debian repository.  I am now running that Steam installation (with a completely different library path).

### Type of Defect

Other

### Describe the Issue

I am unable to install projectM on my Linux desktop from Steam.   I am just getting a "Disk Write Error" during the installation.  It doesn't matter if Steam is installed from the DEB package or the Flatpak.  The library path was different on both attempts and produced the same error.  Other games are installing just fine.
 
![Screenshot_20240818_110908](https://github.com/user-attachments/assets/eaaee5b4-7b4f-4bdd-b991-b40ccd24feed)

The file permissions on the Steam library folder look OK (everything owned by my user).  My system has a healthy NVMe OS drive and no history of I\O problems.

I have to assume the installer is doing something weird like trying to access a path outside of the Steam library or something.  All the resources I've found online say this is a permissions issue, but other games install perfectly fine.

**Comment by kblaschke** [comment] 2024-08-18 17:50
I'm sorry, we can't really help with this issue here.

First of all, how Steam installs an app or game is opaque, as it is all done by the Steam client itself. There is no other installer involved - Steam downloads the required files, decrypts them and then copies the files to your selected install destination. Some games may run some scripts when you first launch the application, but in this case I guess it's really just downloading and copying files.

Second, the projectM core team does not publish the Steam version, even if it says so on Steam. You can [join our Discord server](https://discord.gg/mMrxAqaa3W) and ask the user `@incrementalrage`, he's the one who publishes projectM on Steam. Note he's currently on vacation and will be back in September.

Besides that, from my Steam experience, there are a few things you can try to get more information:
- Run Steam from a terminal (quit the application if it's running), then you'll see a lot of output like errors and such being printed to the terminal, which may help to identify _what exactly_ the issue is as the UI errors are sometimes misleading.
- Check if your Steam installation folder for projectM points to the correct directory. If it is your standard Steam install location, try using a different path, e.g. on a drive with a different filesystem.
- A long shot, but also check if your target filesystem has enough _inodes_ left using the `df -i` command. Should normally be no issue, but I ran into this a few times. If `iUse%` is 99% or 100%, then this may be the problem. Only happens if you have many millions of files on your disk, or a very small filesystem.

As a last resort, you can always try to reach out to Valve's Steam support.

I'll close this issue, as this is no bug in projectM or anything the team here can solve.

**Closed by kblaschke** 2024-08-18 17:50 UTC
Labels: invalid
