### ISSUE TITLE
Just upgraded to macOS Catalina... No more Music Visualizer... How do I use projectM now??

### ISSUE THREAD

**Issue by RainbowShadow98** [projectM-visualizer/projectm#251] opened 2019-10-17 07:35 UTC

**Comment by coast77777777777** [comment] 2019-10-17 17:28
I can build just fine on Catlina, @revmischa can we release for appleTv? Can we agree on $0 price without ads or paywall?

**Comment by revmischa** [comment] 2019-10-17 17:31
AppleTV would be great. Maybe we need to publish an updated build for people on Catalina?

**Comment by revmischa** [comment] 2019-10-17 17:32
ProjectM SDL still runs fine for me without rebuilding on Catalina, so I don't know how to reproduce this sorry.

I did get this though, not sure about why:
![image](https://user-images.githubusercontent.com/245131/67032914-39f1bc00-f11d-11e9-90e7-a5a715e844d7.png)

It shouldn't need this.

**Comment by coast77777777777** [comment] 2019-10-17 17:35
thats probably from the keyboard event manager in SDL. I can open a discussion in valve's SDL community. I have done a few apps in the Apple itunes store for iphone and ipads. I am curious how the appleTV works. Maybe there is a mic in the apple tv?

**Comment by revmischa** [comment] 2019-10-17 17:47
Unless there is some code I'm not aware of, all it does is call https://wiki.libsdl.org/SDL_PollEvent
I don't understand why it would be trying to read keyboard input from the background

**Comment by coast77777777777** [comment] 2019-10-17 23:04
There is also a key handler in the libprojectm object?

**Comment by revmischa** [comment] 2019-10-18 07:17
> There is also a key handler in the libprojectm object?
> […](#)
> > On Oct 17, 2019, at 1:56 PM, Mischa Spiegelmock ***@***.***> wrote: ﻿ Hm, disabling PollEvent still causes it to ask for that. So something somewhere else is trying to capture all keyboard input. Fishy. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

A handler yes but it doesn't poll for any input that I'm aware of

**Comment by revmischa** [comment] 2019-10-23 10:41
Okay that input monitoring issue is fixed in latest libsdl - https://hg.libsdl.org/SDL/rev/6a3b2cc9d66c
Will need to do a new build at some point

**Comment by RainbowShadow98** [comment] 2019-10-25 07:23
Okay so im an idiot with most computers but am decent at figuring it out.

How do I install and run projectM now that there is no iTunes plugin folder because last time I set this up I just dragged the master folder in there and shablamo it worked but where do I need to put the master folder now?

**Comment by RainbowShadow98** [comment] 2019-10-25 07:27
Edit: I see they added the visualizer feature back onto Catalina after initially deleting it but I still need to know where to plug in the master folder?

**Comment by revmischa** [comment] 2019-10-25 11:21
Try the [releases](https://github.com/projectM-visualizer/projectm/releases) instead of master

**Comment by RainbowShadow98** [comment] 2019-10-26 18:58
I was able to install those pkgs but it simply created a folder within Library that's labeled iTunes and then has a plugins folder within that which is housing the projectm.bundle file

I also tried moving the master folder here but it seems its simply not in the correct location. 

I need to figure out where the Music app folder is and see if there is a plugins folder within that

**Comment by RainbowShadow98** [comment] 2019-10-26 19:33
I got the stand alone working at least but would enjoy the use of the plugin

**Comment by revmischa** [comment] 2019-10-26 19:49
The plugin goes in /Library/iTunes/iTunes Plug-ins/
The installer for it should install it there automatically

**Comment by RainbowShadow98** [comment] 2019-10-26 19:50
Yeah correct but iTunes doesn't exist

**Comment by revmischa** [comment] 2019-10-26 19:51
The directory? You can create it
![image](https://user-images.githubusercontent.com/245131/67625179-595ca900-f7ef-11e9-8538-47724d5c1de7.png)

**Comment by RainbowShadow98** [comment] 2019-10-26 19:53
Sorry, yes it will install as the pkg is coded to do but since iTunes doesn't exist this folder becomes dead weight because the Music app isn't looking for it

**Comment by revmischa** [comment] 2019-10-26 19:55
Oh I see okay. Hmm.... does Music support plugins? Can you find some documentation on it?

**Comment by RainbowShadow98** [comment] 2019-10-26 19:58
Since it is so new its hard to find any information on it but even a call with apple support led to nothing it seems apple was incredibly lazy and literally just deleted iTunes and gave us no way to add plug ins to the Music app

But, the music app does still have the visualizers so MAYBE (cus I don't know how any of this works) if I just drop projectM into whatever folder holds the visualizers code files it'll magically appear

**Comment by RainbowShadow98** [comment] 2019-10-26 20:09
Since I have the standalone working anyway though, how do I now go in and edit the files with updates? 

Since its an app file now shouldn't there be a file at Library/ApplicationSupport/projectMSDL

But there isn't so where do I go to add presets and other updates

**Comment by revmischa** [comment] 2019-10-26 20:18
Check out `/usr/local/share/projectM` presets and config should go there

**Comment by coast77777777777** [comment] 2019-10-27 00:39
I am curious if we could request sdl community to implement loopback capture for windows, Linux, and macOS. This build captures your microphone 🎤 but not audio from music app if you listen with headphones.  The system needs operating system audio loopback capture abstracted into libprojectm. Then we can solve many of these issues with less effort for many implementations.

**Comment by revmischa** [comment] 2019-11-10 00:02
> Since it is so new its hard to find any information on it but even a call with apple support led to nothing it seems apple was incredibly lazy and literally just deleted iTunes and gave us no way to add plug ins to the Music app
> 
> But, the music app does still have the visualizers so MAYBE (cus I don't know how any of this works) if I just drop projectM into whatever folder holds the visualizers code files it'll magically appear

Yeah I see that it does have visualizer support still. I wish I knew where those plugins live now in catalina.

**Comment by revmischa** [comment] 2019-11-10 00:06
There is a PlugIns directory inside of Music.app but it's completely unmodifiable, even with sudo

```
❯ sudo cp -r /private/tmp/iTunes\ Plugin.dst/Library/iTunes/iTunes\ Plug-ins/iProjectM.bundle  /System/Applications/Music.app/Contents/PlugIns 
...
cp: /System/Applications/Music.app/Contents/PlugIns/iProjectM.bundle/Contents/Info.plist: No such file or directory
cp: /System/Applications/Music.app/Contents/PlugIns/iProjectM.bundle/Contents/PkgInfo: No such file or directory
```

**Comment by y4rr** [comment] 2019-11-11 01:34
> There is a PlugIns directory inside of Music.app but it's completely unmodifiable, even with sudo
> 
> ```
> ❯ sudo cp -r /private/tmp/iTunes\ Plugin.dst/Library/iTunes/iTunes\ Plug-ins/iProjectM.bundle  /System/Applications/Music.app/Contents/PlugIns 
> ...
> cp: /System/Applications/Music.app/Contents/PlugIns/iProjectM.bundle/Contents/Info.plist: No such file or directory
> cp: /System/Applications/Music.app/Contents/PlugIns/iProjectM.bundle/Contents/PkgInfo: No such file or directory
> ```

You could try this:
Reboot to recovery. Disable System Integrity Protection. Then -
sudo mount -uw /
sudo chown <your username>:staff /System/Applications/Music.app

And then test it 
touch  /System/Applications/Music.app/my_file.txt

**Comment by landendanyluk** [comment] 2019-12-20 00:21
I managed to unlock Music.app's PlugIns directory by disabling SIP, and dragged iProjectM.bundle into that directory, but nothing is showing in the visualizers menu. Is there something I'm missing, or can we assume Music.app doesn't properly support third-party plugins?

**Comment by elliotttate** [comment] 2020-05-24 15:47
The latest ProjectM iTunes installer works almost completely fine out of the box for me with new Music app and Catalina, but it's only one quarter of the window size. The rest is just green:
<img width="1531" alt="CleanShot 2020-05-24 at 10 42 41@2x" src="https://user-images.githubusercontent.com/25666454/82758386-e4b11380-9dab-11ea-9316-2bc0b91e4d65.png">

**Comment by elliotttate** [comment] 2020-05-24 15:49
For some reason, the settings are greyed out on every single visualizer though... 🤔 
<img width="1274" alt="CleanShot 2020-05-24 at 10 48 37@2x" src="https://user-images.githubusercontent.com/25666454/82758440-3194ea00-9dac-11ea-9474-d014d2f17942.png">

**Comment by y4rr** [comment] 2020-05-25 03:49
> The latest ProjectM iTunes installer works almost completely fine out of the box for me with new Music app and Catalina, but it's only one quarter of the window size. The rest is just green:
> <img alt="CleanShot 2020-05-24 at 10 42 41@2x" width="1531" src="https://user-images.githubusercontent.com/25666454/82758386-e4b11380-9dab-11ea-9316-2bc0b91e4d65.png">

Confirm that, can reproduce on my system

**Comment by revmischa** [comment] 2020-05-25 07:46
This is a duplicate of #332 -
It should be fixed in https://github.com/projectM-visualizer/projectm/commit/44ab74e738aea2ae86a719093cd204511665e7aa
Will be released soon

**Closed by revmischa** 2020-05-25 07:46 UTC
