### ISSUE TITLE
jack does not build

### ISSUE THREAD

**Issue by ycollet** [projectM-visualizer/projectm#105] opened 2018-09-20 18:22 UTC
In the current cmake branch, the jack version of projectm is not buildable.
The CMakeLists.txt file is missing in the jack directory.

**Comment by revmischa** [comment] 2018-09-20 19:17
it uses autotools now. a makefile and configure needs to be added for jack.

**Comment by ycollet** [comment] 2018-09-21 08:44
Maybe, in the mean time, you should add back the CMakeLists.txt  file. 
And removes it when the configure script will be ready.

----- Mail original -----
De: "Mischa Spiegelmock" <notifications@github.com>
À: "projectM-visualizer/projectm" <projectm@noreply.github.com>
Cc: "ycollet" <ycollette.nospam@free.fr>, "Author" <author@noreply.github.com>
Envoyé: Jeudi 20 Septembre 2018 21:17:30
Objet: Re: [projectM-visualizer/projectm] jack does not build (#105)



it uses autotools now. a makefile and configure needs to be added for jack.

**Comment by ionenwks** [comment] 2018-10-09 03:46
Is the jack specific version even necessary anymore? I tried to build this again recently (been a few years since last used it) and was annoyed by this at first but then I realized SDL2 has full Jack support now (I did need to build my own libsdl since current Debian omitted the jack support). Set the SDL_AUDIODRIVER=jack connected the ports and there it was, reading the audio seemingly fine. Not that I experimented much with this yet.

**Comment by revmischa** [comment] 2018-10-09 06:51
> add back the CMakeLists.txt  file
Not sure if that's how it works... I think it requires the rest of the project be built with cmake

**Comment by ycollet** [comment] 2018-10-09 07:32
There is two possibility:
- first, you can add back the cmake into the jack directory and the jack part will just require a separate build
- add an autoconf / automake file to build the jack part.

----- Mail original -----
De: "Mischa Spiegelmock" <notifications@github.com>
À: "projectM-visualizer/projectm" <projectm@noreply.github.com>
Cc: "ycollet" <ycollette.nospam@free.fr>, "Author" <author@noreply.github.com>
Envoyé: Mardi 9 Octobre 2018 08:51:43
Objet: Re: [projectM-visualizer/projectm] jack does not build (#105)





add back the CMakeLists.txt file 
Not sure if that's how it works... I think it requires the rest of the project be built with cmake

**Comment by revmischa** [comment] 2018-11-17 12:46
What is the use case for having a dedicated jack version? What do you think about what @ionenwks said?
Feel free to contribute a Makefile.am for the jack version

**Comment by revmischa** [comment] 2019-02-09 21:42
Added jack makefile here - https://github.com/projectM-visualizer/projectm/pull/163 please give it a try!

**Comment by TildeSlashC0re** [comment] 2019-02-10 23:50
```
qprojectM-jack.cpp: In function ‘std::__cxx11::string read_config()’:
qprojectM-jack.cpp:95:10: warning: declaration of ‘out’ shadows a global declaration [-Wshadow]
    FILE *out;
          ^~~
qprojectM-jack.cpp:47:29: note: shadowed declaration is here
 jack_default_audio_sample_t out[1024*1000];
                             ^~~
qprojectM-jack.cpp:91:8: warning: unused variable ‘n’ [-Wunused-variable]
    int n;
        ^
qprojectM-jack.cpp: In function ‘int main(int, char**)’:
qprojectM-jack.cpp:204:7: warning: unused variable ‘projectM_data’ [-Wunused-variable]
  char projectM_data[1024];
       ^~~~~~~~~~~~~
depbase=`echo ConfigFile.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
g++ -DHAVE_CONFIG_H -I. -I../..  -Wall -Wchar-subscripts -Wformat-security -Wpointer-arith -Wshadow -Wsign-compare -Wtype-limits -DDATADIR_PATH=\""/usr/local/share/projectM"\" -I../../vendor  -include ../../config.h -DSYSCONFDIR=\""/usr/local/etc"\" -DPROJECTM_PREFIX=\""/usr/local"\" -DRESOURCE_PREFIX=\""share/projectM"\" -I../../src/libprojectM -I../../src/libprojectM/Renderer -I../../src/projectM-qt  -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/x86_64-linux-gnu/qt5  -fPIC -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/x86_64-linux-gnu/qt5   -g -O2 -pthread -std=c++11 -MT ConfigFile.o -MD -MP -MF $depbase.Tpo -c -o ConfigFile.o ConfigFile.cpp &&\
mv -f $depbase.Tpo $depbase.Po
/bin/bash ../../libtool  --tag=CXX   --mode=link g++  -g -O2 -pthread -std=c++11 -static -fPIC   -o projectM_jack qprojectM-jack.o ConfigFile.o ../projectM-qt/libprojectM_qt.a -ljack -lQt5OpenGL -lQt5Widgets -lQt5Gui -lQt5Core -lGL  -ldl  -pthread ../libprojectM/libprojectM.la -lSDL -lGL  -ldl  -pthread
libtool: link: g++ -g -O2 -pthread -std=c++11 -fPIC -o projectM_jack qprojectM-jack.o ConfigFile.o -pthread -pthread  ../projectM-qt/libprojectM_qt.a -ljack -lQt5OpenGL -lQt5Widgets -lQt5Gui -lQt5Core ../libprojectM/.libs/libprojectM.a -lSDL -lGL -ldl -pthread
/usr/bin/ld: cannot find -lSDL
collect2: error: ld returned 1 exit status
make[3]: *** [Makefile:481: projectM_jack] Error 1
make[3]: Leaving directory '/home/c0re/.build/projectm/src/projectM-jack'
make[2]: *** [Makefile:451: all-recursive] Error 1
make[2]: Leaving directory '/home/c0re/.build/projectm/src'
make[1]: *** [Makefile:521: all-recursive] Error 1
make[1]: Leaving directory '/home/c0re/.build/projectm'
make: *** [Makefile:411: all] Error 2

```

my result so far :<

**Comment by tank-trax** [comment] 2019-02-21 16:13
@revmischa 

I managed to build your JACK version

![projecm screen jack](https://user-images.githubusercontent.com/41337033/53183392-30817580-35c9-11e9-8fa8-d9abc7e82c3a.png)

It works but only has a mono input

the 'n' key for next, 'r' for random and 'p' for previous all are active and functional 

r/clicking on screen does not bring up the menu
double clicking does not enable full screen
has xruns on exit

ERROR: JackEngine::XRun: client = projectM_jack was not finished, state = Triggered
ERROR: JackAudioDriver::ProcessGraphAsyncMaster: Process error

**Comment by tank-trax** [comment] 2019-02-21 18:26
this is the output when run from the terminal 

user@hostname:$ /usr/local/bin/projectM_jack 
dir:/usr/local/share/projectM/config.inp 
reading ~/.projectM/config.inp 
[projectM] config file: /home/user/.projectM/config.inp
[PresetFactory] url is idle://Geiss & Sperl - Feedback (projectM idle HDR mix).milk
No Textures Loaded from /usr/local/share/projectM/textures
No Textures Loaded from /usr/local/share/projectM/textures
engine sample rate: 48000
Connecting to Jack port system:capture_1
Connecting to Jack port system:capture_2
Connecting to Jack port a2j:Midi Through [14] (capture): Midi Through Port-0
Connecting to Jack port a2j:Midi Through [14] (capture): Midi Through Port-1
Connecting to Jack port a2j:Midi Through [14] (capture): Midi Through Port-2
Connecting to Jack port a2j:Midi Through [14] (capture): Midi Through Port-3
Connecting to Jack port a2j:FastTrack Pro [16] (capture): FastTrack Pro MIDI 1

it will start to load the presets once 'n' is pressed

[PresetFactory] url is /usr/share/projectM/presets/Aderrasi - Agitator.milk
[PresetFactory] url is /usr/share/projectM/presets/Aderrasi - Aimless (Gravity Directive Mix).milk
[PresetFactory] url is /usr/share/projectM/presets/Aderrasi - Aimless (Spirogravity Mix).milk
[PresetFactory] url is /usr/share/projectM/presets/Aderrasi - Airhandler (Menagerie Mix).milk

**Comment by revmischa** [comment] 2019-02-21 21:09
cool!

**Comment by tank-trax** [comment] 2019-02-21 21:35
The visualizations work when audio is pumped through the projectM_jack input.

if I may add some suggestions:

1) a stereo input would be nice :-)

2) to figure out how to not have the a2j recognized as Audio (I think this may be the cause of the xrun on closing), as those are connections that would normally be seen in ALSA MIDI but with a2jmidid enabled they can be used with JACK

Note: a few DAWS list this a2j in their Audio configuration sections but it should be in the MIDI section.

======================

Are you planning on developing it further for JACK? if so I would be interested to assist with testing. FYI, I use Debian 9 with KXStudio repos added.

**Comment by tank-trax** [comment] 2019-02-21 21:38
I also had to install the following to complete the build

sudo apt-get install libsdl-image1.2-dev libsdl-ttf2.0-dev

**Comment by revmischa** [comment] 2019-02-22 09:00
PRs very welcome! :)

**Comment by tank-trax** [comment] 2019-03-01 20:57
built this successfully, installation went well but had to create a shortcut/menu entry 

all keyboard shortcuts work

Settings -> Configure projectM all good
there is no entry for Audio settings
Audio is still mono -> ideally it would be stereo

first time I built it with ./configure the visualizations would not load or play
second time used ./configure --enable-gles and it worked

my apologies I do not know how to create/open a new a PR

**Comment by revmischa** [comment] 2019-03-03 09:35
> second time used ./configure --enable-gles and it worked
Noted in #168

**Comment by revmischa** [comment] 2019-03-03 09:36
Jack build support is in master now. Please test it out!
If you have feature requests feel free to open tickets for them specifically so we can track them. Or better yet, contribute some code! 
You can read about PRs on [GitHub's help pages](https://help.github.com/en/articles/creating-a-pull-request)

**Closed by revmischa** 2019-03-03 09:36 UTC
Labels: good first issue
