### ISSUE TITLE
Failed to find matching components of a complete Qt installation

### ISSUE THREAD

**Issue by Motsyo** [projectM-visualizer/projectm#550] opened 2021-10-30 14:30 UTC
```
checking for Qt... Info: creating stash file /usr/src/tmp/tmp.t0Kv7ukj6R/.qmake.stash
rmdir: failed to remove '/usr/src/tmp/tmp.t0Kv7ukj6R': Directory not empty
yes:
    QT_CXXFLAGS=-pipe -O2 -Wall -Wextra -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -I../../../include/qt5 -I../../../include/qt5/QtOpenGL -I../../../include/qt5/QtWidgets -I../../../include/qt5/QtGui -I../../../include/qt5/QtCore -I. -I../../../lib64/qt5/mkspecs/linux-g++ 
    QT_DIR=/usr/lib64
    QT_LIBS=/usr/lib64/libQt5OpenGL.so /usr/lib64/libQt5Widgets.so /usr/lib64/libQt5Gui.so /usr/lib64/libQt5Core.so -lGL -lpthread  
    QT_UIC=/usr/share/qt5/bin/uic
    QT_MOC=/usr/share/qt5/bin/moc
    QT_RCC=/usr/share/qt5/bin/rcc
    QT_LRELEASE=/usr/share/qt5/bin/lrelease
    QT_LUPDATE=/usr/share/qt5/bin/lupdate
checking correct functioning of Qt installation... failure
configure: error: Failed to find matching components of a complete
                  Qt installation. Try using more options,
                  see ./configure --help.
error: Bad exit status from /usr/src/tmp/rpm-tmp.84195 (%build)
```
[build.log](https://github.com/projectM-visualizer/projectm/files/7446785/build.log)
[config.log](https://github.com/projectM-visualizer/projectm/files/7446786/config.log)
[qt5_list.log](https://github.com/projectM-visualizer/projectm/files/7446787/qt5_list.log)
I need help...

**Comment by kblaschke** [comment] 2021-11-04 16:43
Could you try using the CMake build system instead of the configure script?

The autoconf version used in projectM is quite ancient, so it might not be up to recent Qt changes. It'll be removed soon anyways in favor of CMake.

**Comment by Motsyo** [comment] 2021-11-04 20:02
> Could you try using the CMake build system instead of the configure script?
> 
> The autoconf version used in projectM is quite ancient, so it might not be up to recent Qt changes. It'll be removed soon anyways in favor of CMake.

I cannot find any CMakeLists.txt in source files...

**Comment by kblaschke** [comment] 2021-11-04 23:11
It's in the top-level directory.

You probably need to check out [or download the master branch](https://github.com/projectM-visualizer/projectm/archive/refs/heads/master.zip) from Git, as the release downloads do not yet contain the changes.

**Comment by Motsyo** [comment] 2021-11-05 06:25
> It's in the top-level directory.
> 
> You probably need to check out [or download the master branch](https://github.com/projectM-visualizer/projectm/archive/refs/heads/master.zip) from Git, as the release downloads do not contain the recent changes.

[build.log](https://github.com/projectM-visualizer/projectm/files/7481008/build.log)
Last git with cmake...

**Comment by kblaschke** [comment] 2021-11-05 09:28
In this case, it looks like `/usr/lib64/libSDL2main.a` is missing. It should always be built, but possibly wasn't installed properly.

**Comment by Motsyo** [comment] 2021-11-06 10:05
> In this case, it looks like `/usr/lib64/libSDL2main.a` is missing. It should always be built, but possibly wasn't installed properly (It's always built as a static library, which in some cases might be filtered out if the build script only installs shared libraries).

This library is missing in my distro, so I specified
-DENABLE_STATIC_LIB=OFF -DENABLE_SHARED_LINKING=ON

But... The linker still requires a static library.

**Comment by kblaschke** [comment] 2021-11-07 13:24
These two flags only tell the build system to link libprojectM either as a static or shared library, but it does not influence the linkage of libSDL2. libSDL2main.a isn't the main SDL2 library, but a small static lib that contains the `main()` function for the projectMSDL application. Without this library, it won't work or link as it's missing the entry point.

Since libSDL2main.a (and also libSDL2.a, which is also missing in the ALT Linux SDL2-devel package) should be part of any development package, there's not much we can do from projectM's side if the distro's packages aren't complete.

You basically have two options here:

1. Build SDL2 yourself on ALT and use it to build projectM instead of the system package. The resulting binaries will still run fine against the system's libSDL2.so, and the static libs will by design just become part of the projectMSDL executable.
2. Try to kindly ask the package maintainer (Denis Nazarov, nenderus@altlinux.org) to add the mising static libraries to the development package.

**Comment by kblaschke** [comment] 2021-11-07 13:32
If you deciode to build SDL2 yourself, use this approach:

1. Download the latest release .tar.gz (2.0.16 as of now) from the [SDL2 Releases page](https://github.com/libsdl-org/SDL/releases)
2. Extract the contents somewhere. For a minimal version, only the same dependencies are required that projectM needs.
3. Create a build directory somewhere and execute CMake in it, then build and install:
```bash
cmake -DCMAKE_INSTALL_PREFIX=/path/to/install/SDL2 /path/to/SDL2/sources
cmake --build . --config Release --target install -- -j4
```
4. Point projectM's build system to your self-built SDL2 installation directory using CMAKE_PREFIX_PATH:
```bash
cmake -DCMAKE_PREFIX_PATH=/path/to/install/SDL2 [other projectM build options] /path/to/projectM/sources
```
CMake should then use your own version instead of the system one. You can also uninstall the SDL2-devel package to be totally sure.

**Comment by Motsyo** [comment] 2021-11-08 12:00
>     2\. Try to kindly ask the package maintainer (Denis Nazarov, [nenderus@altlinux.org](mailto:nenderus@altlinux.org)) to add the mising static libraries to the development package.

Ok. I can create a bug report for the SDL2 package, but is it really impossible to correct the source code so that the linker does not require a static library during dynamic linking?

**Comment by kblaschke** [comment] 2021-11-08 18:27
In this case, no, because libSDL2main doesn't exist as a shared library. It can't, because it actually contains the `main()` function. It is not libSDL2.so, which is indeed linked dynamically.

You could of course patch the sources, write your own main function and remove the library from the linker command. The missing library is always a part of the SDL2 development files (note only libSDL2.a is optional, but should also be available for those who want to link it statically), so if it's not packaged, the package maintainer did something wrong, not any project depending on SDL2 and using the SDLmain library.

**Comment by kblaschke** [comment] 2021-11-16 09:28
Closing this issue as the above problems are not projectM-related and we can't fix them from here.

If you have additional questions, you can [join the projectM Discord server](https://discord.gg/tpEuywB) and talk to us there.

**Closed by kblaschke** 2021-11-16 09:28 UTC
Labels: qt-frontend
