### ISSUE TITLE
projectMSDL SIGSEGV on Alpinelinux

### ISSUE THREAD

**Issue by trphx** [projectM-visualizer/projectm#427] opened 2020-10-22 14:30 UTC
I built projectM on alpine linux x86_64 5.4.43-1-lts with sdl (once with and without multiprocessing).
The default projectM in projectMSDL preset works as intended.
projectMSDL cannot switch to any other preset and throws SIGSEGV when pressing m.
It prints:
>13770: signal: sys: segmentation violation

GDB output without debugging information:
>Thread 1 "projectMSDL" received signal SIGSEGV, Segmentation fault.
>
>std::__cxx1::basic_string (__str=...,this=0x7fffffffe398)
>
>    at /usr/include/c++/9.3.0/ext/new_allocator:89

GDB output with debugging information:
>Thread 1 "projectMSDL" received signal SIGSEGV, Segmentation fault.
>
>0x000055555557559a in projectM::getPresetName[abi:cxx11](unsigned int) const ()

I reproduced this in v3.1.8 and v3.1.7.

**Comment by kblaschke** [comment] 2021-06-09 16:34
Can also reporoduce the behaviour on Gentoo Linux, still happens with the latest version. Removing the "offending" code only makes the program crash shortly after that in a completely different part of the codebase.

Looking at the memory, it seems there is some (heap or stack) corruption happening at some point, possibly overwriting some pointers.

I'll try running valgrind on it to see if that brings up some clue.

**Comment by kblaschke** [comment] 2021-06-09 20:53
@trphx Can you please re-verify whether the problem still exists for you in current master?

**Comment by trphx** [comment] 2021-06-11 19:10
Now I get different debugging output.

GDB output without debugging information:
```
Thread 1 "projectMSDL" received signal SIGSEGV, Segmentation fault.
0x0000555555586066 in projectM::populatePresetMenu() ()
```
GDB output with debugging information:
```
Thread 1 "projectMSDL" received signal SIGSEGV, Segmentation fault.
0x00007ffff7d14f92 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::
basic_string(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    () from /usr/lib/libstdc++.so.6
```

**Comment by trphx** [comment] 2021-06-11 20:03
I added a few debugging statements to the function
```
794a795
>     puts("CALLED populatePresetMenu()");
795a797
>         puts("SEARCH");
818a821
>             puts("PAGE");
840c843
<     }*/
---
>     }
```
This reveals the control flow to be highly unusual (note that this is compile without multithreading):
```
CALLED populatePresetMenu()
INFO: Using config from /root/.projectM/config.inp
INFO: Opened audio capture device index=0 devId=2: My Speakers
CALLED populatePresetMenu()
SEARCH
PAGE
13981: signal: sys: segmentation violation
```

After using a few other statements and seperating some expressions, it seems like the function fails at line 836 in getPresetName().
getPresetName() is defined as a method of PresetLoader and returns a string from the vector _presetNames.
The segfault presumably occurs when _presetNames is accessed.

**Comment by kblaschke** [comment] 2021-06-11 20:55
Thanks for the great research!

No totally obvious issues here, the only problem I could possibly see is if `renderer->m_activePresetID` has a larger value than than `m_presetLoader->size() - 1`, calling `getPresetName()` leads to an out-of-bounds access in the preset vector. Changing line 821 to `if (m_presetPos->lastIndex() >= m_presetLoader->size())` would fix that border case - or possibly better, adding a bounds check in the getter function.

**Comment by trphx** [comment] 2021-06-11 22:05
/stg/af/bina

**Comment by trphx** [comment] 2021-06-11 22:05
mplayer /stg/af/binu

**Comment by trphx** [comment] 2021-06-12 06:37
A segfault also occurs when element 0 is accessed or capacity() is called, but it's not a null pointer, so some function must free it.
However commenting out clearPlaylist(), removePreset() and the clear() code still shows the described behaviour.

**Comment by kblaschke** [comment] 2021-06-12 13:01
Might also be another stack corruption, similar to the one I recently fixed. Will see if I can reproduce the issue somehow in the next days and try to find the culprit.

**Comment by kblaschke** [comment] 2021-08-23 16:05
Most menu issues were fixed. There's still one small bug in the function that populates the preset search list if the number of total presets is less than fit on one screen, which I'll fix soon.

**Comment by kblaschke** [comment] 2021-11-07 00:22
@trphx could you please retest with the current master to see if there's any segfault issue left?

I haven't seen any crashes since the preset playlist issue was merged, so it's hopefully running stable now.

**Comment by kblaschke** [comment] 2021-11-19 14:04
No further feedback on that issue, closing it as the crashes in the above mentioned functions were fixed.

If you still experience crashes with latest master, please create a new issue with a recent stack trace.

**Closed by kblaschke** 2021-11-19 14:04 UTC
Labels: bug, important
