### ISSUE TITLE
Segfault in current master

### ISSUE THREAD

**Issue by DanielHeath** [projectM-visualizer/projectm#411] opened 2020-08-26 22:42 UTC
Running revision 460c8c87a19319fa5a6ee7484db81242c053b601

I am rerunning it now with `ulimit -c unlimited` to try and get you a core dump too.

Here's the last output:
```
Failed to locate texture devboxb
Texture loading error for: devboxb
Failed to locate texture devboxb
Texture loading error for: devboxb
presets_community/suksma - never waership.milk(85) : Undeclared identifier 'sampler_devboxb'
Failed to parse HLSL(step2) Comp shader
Source: 
uniform float4 texsize_pw_main;
<SNIP bunch of code>
handleFailedPresetSwitch
token prefix is g
token prefix is g
token prefix is g
token prefix is m
token prefix is m
token prefix is m
token prefix is m
token prefix is m
token prefix is m
token prefix is m
projectM-pulseaudio: Parser.cpp:1226: static Expr* Parser::parse_infix_op(std::istream&, token_t, TreeExpr*, MilkdropPreset*): Assertion `gen_expr' failed.
Aborted (core dumped)

```

**Comment by milkdropper** [comment] 2020-08-30 14:29
I could not reproduce with projectM-SDL on suksma - never waership.milk, so I think this could be specific to pulseaudio. Tagging this issue as pulseaudio.

**Comment by DanielHeath** [comment] 2020-09-01 07:02
I haven't been able to reproduce this after several more days running, so I don't have any further details for you.


Thanks,
Daniel Heath

**Comment by milkdropper** [comment] 2020-09-01 12:25
Thanks for the followup. I'll close the issue.

**Closed by milkdropper** 2020-09-01 12:25 UTC
