### ISSUE TITLE
Preset nWaveMode off-by-one?

### ISSUE THREAD

**Issue by tomporter518** [projectM-visualizer/projectm#620] opened 2022-05-02 21:42 UTC
**Describe the bug**
Some presets fail to render or render differently since the waveform refactor. Most notably are two I use:
.../presets-cream_of_the_crop/Waveform/Wire Flat/Bmelgren & Krash - Rainbow Orb Peacock (Lonely Signal Gone Mad Mix).milk
only produces a completely black screen,
and:
.../presets-cream_of_the_crop/Reaction/Liquid Gradient/Krash and Fvese - Molten Indecision (Fvese Remix).milk
which renders but is more constrained to the center of the screen and the color range isn't as dynamic.

I have tracked it down to what I think is a change in the way the nWaveMode value is handled. A change to the enum detailing the wave forms is now 0-based, when it was previously 1-based. By decrementing the nWaveMode in the affected presets by 1, I have been able to get the two previously mentioned presets to function as I think they did before.

**Screenshots**
None

**Desktop (please complete the following information):**
 - Application: self built libprojectM and frontend-qt
 - OS: Linux/Fedora 35
 - Version: latest git (5583a5e)

**Additional context**
See commit and comment: [1ee932a](https://github.com/projectM-visualizer/projectm/commit/1ee932a23c3ca3cbc12d055b8492b6f7a83ad9f6#r72710975)

**Comment by kblaschke** [comment] 2022-05-03 15:24
Using the test presets in the repo, which have all wavemodes from 0 to 7, I can't see any issues with the actual waveform shape. There are some differences in brightness and blending, which is a known issue, but wavemode 6 renders as a single-channel line in both Milkdrop and projectM. Also, Milkdrop's preset authoring guide states for the waveform parameter:

```
    wave_mode      yes    0,1,2,3,4,5,6,7  controls which of the 8 types of waveform is drawn
```

So the parameter is actually 0-based, and (as my tests before the mentioned change were carried out) projectM's implementation _was_ off by +1 before and is now correct.

There are many other issues with preset rendering though that might cause presets to render incorrectly or even totally black/broken. Here's an incomplete list:
- Waveform rotation & offsets are not correct in some presets, as Milkdrop & projectM use different rendering APIs with different coordinate systems.
- Some waveform modes render way too dark in OpenGL, probably being smoothed too much or something else is wrong here.
- Blend modes are not working exactly the same between Milkdrop and projectM, causing some presets to render either too bright or too dark.
- The equation parser has some missing features and known errors, e.g. it doesn't support loops, megabuf and some operators like `+=`.
- Equation variable persistency might not be exactly the same as in Milkdrop, which can affect presets that define user variables and need those to be persist across frames and between wave/shape code.

I've already started a branch to rewrite the preset equation parser so it can support all the features Milkdrop has in ns-eel2. This will also include a better state machine for variables, unit tests and other improvements to make sure the code is parsed & executed in the same way (just not as fast, sadly) as in Milkdrop.

Then there's the mentioned issue with coordinate system translation. I've got an idea to solve this by applying a transformation matrix in the vertex shader, so the CPU part of the preset renderer can work with DirectX coordinates and then the GPU will transform them uniformly into OpenGL coordinates.

Blend modes and other effects will require fine tuning, one effects after the other. For this, more test presets will be required to have a simple test case per effect or feature.

All in all, it's still a lot of work that must be done before projectM has full and nearly-perfect Milkdrop compat. Currently, the team's focus is on improving the C API into a state we can release as projectM 4.0. After that is done, I'll immediately shift focus back on fixing all these compat issues.

I'm closing this issue as the nWaveMode value is not the cause of the issue, but possibly one or more of the other issues.

**Closed by kblaschke** 2022-05-03 15:24 UTC
