### ISSUE TITLE
projectM Qt PulseAudio: configure: error: Failed to find matching components of a complete Qt installation. Try using more options, see ./configure --help.

### ISSUE THREAD

**Issue by fvdfgrgtg42etgfw** [projectM-visualizer/projectm#381] opened 2020-07-22 14:34 UTC
As it has been for at least a year, compiling projectM on Ubuntu is a rabbit hole of incompatibilities, manual package downloads, and browser tabs. Today, I tried compiling projectM Qt PulseAudio (latest version 3.1.3) on Ubuntu 20.04. I fixed the libglm error, but here comes this vague "checking correct functioning of Qt installation... failure/configure: error: Failed to find matching components of a complete Qt installation. Try using more options, see ./configure --help." with qt5-default apparently already the latest version.

**Comment by Button4Button** [comment] 2020-07-22 15:06
Lol I tried exactly the same on Mint 20 this morning since I’ve just
upgraded all my dozen or so machines.

I got as far as the libglm error and sighed. I then recalled that there’s a
set of command line parameters that just worked before that aren’t in the
Readme or webpage.   I can’t find them and need to go back through emails
to find them and try again.

I’d be very happy to update some docs or similar if it means less hassle
for ubu Linux folks in future.

**Comment by revmischa** [comment] 2020-07-25 07:26
Can you please share what you are running and the output around the error message?
I am running Ubuntu 20.04. I can build v3.1.5 with simply running `./configure && make -j8`

```
checking for shmat... yes
checking for IceConnectionNumber in -lICE... yes
checking for Qt... Info: creating stash file /tmp/tmp.y5VMV6RYv7/.qmake.stash
rmdir: failed to remove '/tmp/tmp.y5VMV6RYv7': Directory not empty
yes:
    QT_CXXFLAGS=-pipe -O2 -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtOpenGL -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ 
    QT_DIR=/usr/lib/x86_64-linux-gnu
    QT_LIBS=/usr/lib/x86_64-linux-gnu/libQt5OpenGL.so /usr/lib/x86_64-linux-gnu/libQt5Widgets.so /usr/lib/x86_64-linux-gnu/libQt5Gui.so /usr/lib/x86_64-linux-gnu/libQt5Core.so /usr/lib/x86_64-linux-gnu/libGL.so -lpthread  
    QT_UIC=/usr/bin/uic
    QT_MOC=/usr/bin/moc
    QT_RCC=/usr/bin/rcc
    QT_LRELEASE=/usr/bin/lrelease
    QT_LUPDATE=/usr/bin/lupdate
checking correct functioning of Qt installation... success
checking for libpulse... yes
checking for jack... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating src/libprojectM/Makefile
config.status: creating src/libprojectM/Renderer/Makefile
config.status: creating src/libprojectM/NativePresetFactory/Makefile
config.status: creating src/libprojectM/MilkdropPresetFactory/Makefile
config.status: creating src/libprojectM/libprojectM.pc
config.status: creating src/NativePresets/Makefile
config.status: creating src/projectM-sdl/Makefile
config.status: creating src/projectM-emscripten/Makefile
config.status: creating src/projectM-qt/Makefile
config.status: creating src/projectM-pulseaudio/Makefile
config.status: creating src/projectM-jack/Makefile
config.status: creating src/projectM-test/Makefile
config.status: creating src/libprojectM/config.inp.in
config.status: creating config.h
config.status: config.h is unchanged
config.status: executing depfiles commands
config.status: executing libtool commands
config.status: executing libtool-rpath-patch commands

projectM v3.1.5
=====

prefix:                 /usr/local
sysconfdir:             ${prefix}/etc
libdir:                 ${exec_prefix}/lib
includedir:             ${prefix}/include

compiler:               gcc
cflags:                  -g -O2 -pthread -Wall -Wchar-subscripts -Wformat-security -Wpointer-arith -Wshadow -Wsign-compare -Wtype-limits -DDATADIR_PATH=\""$(pkgdatadir)\"" -I$(top_srcdir)/vendor
cxxflags:               -g -O2 -pthread -std=c++11
libs:                   -lGL  -ldl  -pthread -lQt5Gui -lQt5OpenGL
ldflags:                

- - -

Applications:
=====

libprojectM:            yes
Threading:              yes
SDL:                    no
Qt:                     yes
Pulseaudio:             yes
Jack:                   yes
OpenGLES:               no
Emscripten:             no
llvm:                   no
Preset subdirs:         no
```

**Comment by revmischa** [comment] 2020-07-25 07:55
Let's try to improve the documentation #383 
What need to be added/changed?

**Comment by revmischa** [comment] 2020-07-26 20:45
https://github.com/projectM-visualizer/projectm/pull/387 Should fix whatever glm issue you were seeing

**Comment by Button4Button** [comment] 2020-07-27 10:51
Thanks for the fix.... my overall lack of deep tech knowledge should be fully taken into account here.. .
I'm on Mint 20 (ubu 18.04).....  the configure libglm missing error goes away once you install the **"Build-essential"** package via Software Manager. 
Configure and make work successfully for both 3.1.3 and 3.1.6 however only projectMSDL actually works (which I'm really pleased about) though CTRL-M does not bring up the Menu whilst other shortcuts do work (N,P,F etc) 
The other projectM variants all fail with the same error 
Failed to link program: error: vertex shader lack 'main'

**Comment by kblaschke** [comment] 2021-06-14 15:29
Since that comment, there were multiple fixes regarding shaders etc. and this issue is different from the original build failure, which has been fixed already. So I'm closing the issue.

If you still see the shader error in a recent version, please feel free to file a new issue with details (hardware, OS, preset, log output) that help reproduce the problem.

**Closed by kblaschke** 2021-06-14 15:29 UTC
