### ISSUE TITLE
Save visualisation as video

### ISSUE THREAD

**Issue by swschilke** [projectM-visualizer/projectm#432] opened 2020-11-18 11:50 UTC
Hallo,

it would be really nice to be able to save an audio visualisation as a video file.

Kind regards

.

**Comment by Iiridayn** [comment] 2020-12-14 23:24
Possible duplicate of #205.

**Comment by revmischa** [comment] 2020-12-15 08:35
PRs are very welcome!

**Closed by revmischa** 2020-12-15 08:35 UTC

**Comment by swschilke** [comment] 2020-12-15 08:40
> PRs are very welcome!

Hallo, what is the meaning of that? Sorry the meaning of PR is unknown to me.

Kind regards 

.

**Comment by revmischa** [comment] 2020-12-15 08:44
It is how one contributes changes or improvements to an open-source project
https://guides.github.com/activities/hello-world/
