### ISSUE TITLE
windows binary release

### ISSUE THREAD

**Issue by nicolasjinchereau** [projectM-visualizer/projectm#98] opened 2018-08-27 05:59 UTC
Are there any plans to add a Windows binary to the releases, either as a standalone or VLC plugin?

**Comment by revmischa** [comment] 2018-08-27 06:33
Sure, someone needs to just do it. Want to? I don’t have windows.

**Comment by jbkempf** [comment] 2018-08-27 15:05
I've started to port projectM 3 to VLC, but there are a lot of warnings and compilation issues.

We'll get to it, though.

**Comment by revmischa** [comment] 2018-08-27 15:13
Excellent, let us know if we can help out!

**Comment by nicolasjinchereau** [comment] 2018-08-27 19:46
I would help if I could, but I don't know how VLC plugins work, and wouldn't know how to interface with system audio if I tried to make a standalone build. If porting the code as a library is a blocker, I could probably help with that.

**Comment by mancoast** [comment] 2018-09-02 19:59
I can contribute, where to start?

**Comment by revmischa** [comment] 2018-09-02 20:38
Start with the GLSL branch #26 (soon to be merged to master). 

I don't know if there is some way to use autotools on windows?  

I can write up how to build projectM from scratch if that'll be helpful

**Comment by mancoast** [comment] 2018-09-02 20:47
Yea please provide build instructions. I will identify/resolve gaps and get the system built on cloud using appveyor.

**Comment by revmischa** [comment] 2018-09-02 21:07
Is this helpful at all? Let me know if you have any questions or need more details
https://github.com/projectM-visualizer/projectm/blob/bbc88deb5bd82bd55dd2d67ae5427679a2cd7b09/BUILDING.md

**Comment by mancoast** [comment] 2018-09-02 21:52
Looks good, thanks.  I will open new issues as required.

**Comment by dzarda** [comment] 2018-12-02 21:14
I managed to get the thing compiled on Cygwin with --enable-sdl. Ended up with the following cyg packages installed (some may not be required):
> autoconf,autoconf,automake,gcc-g++,libGLESv2-devel,libSDL2-devel,libglut-devel,libtool,make,pkg-config

Also,
- I added local implementations of `strdup` and `strcasecmp` in hlslparser/src/Engine.cpp to evade nonstandardness bs
- Simplified `#ifdef WIN32` platform-dependent include logic (needed for both __unix__ and WIN32 macros at the same time)
- Added two includes to config.h: `#include <alloca.h>` and `<ctype.h>`

Also, set the GL_LIBS variable before configure:
- `GL_LIBS=-lglut\ -lglu\ -lgl\ -lopengl32`
- `export GL_LIBS`

Will provide a PR if this way proves valid.

---

However, upon execution, I get the following output. My knowledge ends here. Does anybody know what may be wrong?

```
INFO: GL_VERSION: (null)
INFO: GL_SHADING_LANGUAGE_VERSION: (null)
INFO: GL_VENDOR: (null)
[projectM] config file: /usr/local/share/projectM/config.inp
Failed to compile shader 'Vertex: v2f_c4f'. Error:
Failed to compile shader 'Fragment: v2f_c4f'. Error:
Failed to link program:
Failed to compile shader 'Vertex: v2f_c4f_t2f'. Error:
Failed to compile shader 'Fragment: v2f_c4f_t2f'. Error:
Failed to link program:
Failed to compile shader 'Vertex: blur1'. Error:
Failed to compile shader 'Fragment: blur1'. Error:
Failed to link program:
Failed to compile shader 'Vertex: blur2'. Error:
Failed to compile shader 'Fragment: blur2'. Error:
Failed to link program:
[PresetFactory] url is idle://Geiss & Sperl - Feedback (projectM idle HDR mix).milk
      1 [] projectMSDL 14368 cygwin_exception::open_stackdumpfile: Dumping stack trace to projectMSDL.exe.stackdump
```

**Comment by dzarda** [comment] 2018-12-02 22:38
It is indeed the SDL application with the latest master.

**Comment by revmischa** [comment] 2018-12-03 01:43
Is SDL compiled with openGL support and other required video pieces?

**Comment by dzarda** [comment] 2018-12-06 22:07
I'm looking at that now. Dependency Walker shows following dependencies, where CYGSDL2-2-0-0.DLL seems to have no GL deps. Suspicious.

c:\tools\cygwin\bin\PROJECTMSDL.EXE:
- c:\tools\cygwin\bin\CYGWIN1.DLL
- c:\tools\cygwin\bin\CYGGL-1.DLL
- c:\tools\cygwin\bin\CYGSDL2-2-0-0.DLL
  - c:\tools\cygwin\bin\CYGWIN1.DLL
  - c:\windows\system32\ADVAPI32.DLL
  - c:\windows\system32\KERNEL32.DLL
  - c:\windows\system32\WINMM.DLL
- c:\tools\cygwin\bin\CYGGCC_S-SEH-1.DLL
- c:\tools\cygwin\bin\CYGSTDC++-6.DLL
- c:\windows\system32\KERNEL32.DLL

One way may be compiling SDL from source, but my first try at this generates SDL2.dll, not CYGSDL2.dll as seems to be required.

Or trying the MinGW or MSVC way. Tips needed.

**Comment by mancoast** [comment] 2018-12-06 22:37
I would like to assist. Have you tried msvc?

**Comment by dzarda** [comment] 2019-01-05 18:33
IMO there are multiple ways ahead regarding Windows:
1. Some kernel-level developer needs to step up and make this work (unlikely)
2. We might try to go the MSVC way. Aside from the apparent need (?) of managing the project files/configuration in Visual Studio <xml> in parallel with the ./configure pipeline, there may be hurdles unknown to me.
3. The emscripten/wasm way might prove to be the way forward.

**Comment by mancoast** [comment] 2019-03-17 15:49
the system is barely able to compile on windows (I had to resurrect/modify the old cmake build to regenerate msvc projects and solutions). The SDL2 does not work with my hardware so I cannot test that part, but if I set the fake_audio, it works great! However, the build did require many changes that need preprocessor definitions to prevent breakage of other operating systems. What are the maintenance plans for this project to keep the windows build files in sync with autogen?

**Comment by revmischa** [comment] 2019-03-17 15:53
amazing thanks

On macos I have an Xcode workspace that was mostly straightforward to set up and keep in sync with things. Don’t know if something similar on Windows is easy or not. 

Of course a cross platform solution would be nice. 

Someone is working on seeing if meson would work. Don’t know if it works with windows.

**Comment by dzarda** [comment] 2019-03-17 21:48
@mancoast Sweet, mind releasing the changed you made?

**Comment by mancoast** [comment] 2019-03-17 22:03
Absolutely! I need to finish the ftgl nuget release to finish the appveyor continuous integration. After the build is on the cloud and verified, I will PR

**Comment by mancoast** [comment] 2019-03-21 22:35
https://github.com/projectM-visualizer/projectm/pull/181

Ready to go

**Comment by mancoast** [comment] 2019-03-22 19:43
https://github.com/projectM-visualizer/projectm/pull/182 initiated windows x64 continuous integration. @revmischa can you please enable appveyor to build on this repo? then each commit to this repo will automatically generate binary archives for windows.

**Comment by revmischa** [comment] 2019-03-23 08:10
Sure, just tell me what to do

**Comment by mancoast** [comment] 2019-03-23 13:43
Ok, first step is to sign into appveyor.com using github credentials. 

Then you can create a new appveyor “project” for the projectm repo. That’s all! It should automatically read the config settings from the yaml file.

**Comment by revmischa** [comment] 2019-03-23 16:07
Ok done - not sure if you can view it or not https://ci.appveyor.com/project/revmischa/projectm/builds/23306362/job/6qtay8siv0o0eptx

**Comment by mancoast** [comment] 2019-03-23 16:22
Looks great! The windows binary release is under the “artifacts”.

**Comment by dzarda** [comment] 2019-03-26 10:25
Great stuff, it works!

**Comment by dzarda** [comment] 2019-04-01 20:29
Real input working confirmed:
- Enabled *Stereo Mix* and disabled all other input devices
- Turned FAKE_AUDIO back off

**Comment by revmischa** [comment] 2019-04-02 06:31
awesome @dzarda want to post a PR with changes/docs?

**Closed by revmischa** 2019-04-02 06:31 UTC
Labels: good first issue
