### ISSUE TITLE
Steam ProjectM issue

### ISSUE THREAD

**Issue by orien3243** [projectM-visualizer/projectm#429] opened 2020-11-01 07:54 UTC
So ProjectM on steam makes projectM really easy to install even on Linux. The problem is it won't sync up these visuals to audio playing on my computer or even via a mic. I left a comment in the steam community page and its gone unanswered since August. So I figured I would post it here just in case. 

Pulse audio also has this nice feature in where I can also adjust the volume of running applications such as chrome or my audio player and set the audio volume there. However pulse audio does not even see the projectm application from steam. (This is odd because the compiled version of projectm on my *buntu installation shows up pulse audio's mixer)

How to reproduce the issue?

0. use Ubuntu (or any variant such as Kubuntu or Lubuntu in my case with pulseaudio)

1. install steam and projectm

2. launch projectm

3. "no input devices found" 

4. press Ctrl+I 

5. Crash

Terminal output

`joedoe47@greatfox2:~/.local/share/Steam/steamapps/common/projectM$ ./projectM 
INFO: GL_VERSION: 3.2.0 NVIDIA 435.21
INFO: GL_SHADING_LANGUAGE_VERSION: 1.50 NVIDIA via Cg compiler
INFO: GL_VENDOR: NVIDIA Corporation
INFO: Using data directory: /usr/local/share/projectM
INFO: created ~/.projectM/config.inp successfully
[projectM] config file: /home/joedoe47/.projectM/config.inp
INFO: Using config from /home/joedoe47/.projectM/config.inp
CRITICAL: No audio capture devices found
fps: 29

joedoe47@greatfox2:~/.local/share/Steam/steamapps/common/projectM$ ./projectM --help
INFO: GL_VERSION: 3.2.0 NVIDIA 435.21
INFO: GL_SHADING_LANGUAGE_VERSION: 1.50 NVIDIA via Cg compiler
INFO: GL_VENDOR: NVIDIA Corporation
INFO: Using data directory: /usr/local/share/projectM
INFO: created ~/.projectM/config.inp successfully
[projectM] config file: /home/joedoe47/.projectM/config.inp
INFO: Using config from /home/joedoe47/.projectM/config.inp
CRITICAL: No audio capture devices found
fps: 29
INFO: Displaying preset: Idiot - MOTIVATION!.milk
INFO: Opened audio capture device index=0 devId=2: (null)
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
Aborted (core dumped)
`

Hopefully I am just missing something basic here.

**Comment by revmischa** [comment] 2020-11-01 09:32
The problem is it doesn't detect any audio input devices on your system. Any idea why? Maybe it needs some permission?

**Comment by orien3243** [comment] 2020-11-01 15:01
ha ha EXCELLENT! Yeah it seems thats all it needed. 

`joedoe47@greatfox2:~/.local/share/Steam/steamapps/common/projectM$ sudo ./projectM 
[sudo] password for joedoe47: 
INFO: GL_VERSION: 3.2.0 NVIDIA 435.21
INFO: GL_SHADING_LANGUAGE_VERSION: 1.50 NVIDIA via Cg compiler
INFO: GL_VENDOR: NVIDIA Corporation
INFO: Using data directory: /usr/local/share/projectM
[projectM] config file: /root/.projectM/config.inp
INFO: Using config from /root/.projectM/config.inp
INFO: Opened audio capture device index=0 devId=2: HDA Intel PCH, ALC887-VD Analog
fps: 35
INFO: Displaying preset: Rovastar - Xtal.milk`

Started doing all its visuals like expected. There is still a few issues but probably because I am running the application as root.

AFAIK some apps when run with the sudo command act in unexpected ways. I'll try to add my user to pulse and those issues will go away.

**Comment by orien3243** [comment] 2020-11-01 19:28
Okay so here is what I noticed. I am reopening this because IDK what the next step is so, my apologies. 

While projectM now detects the two card outputs  "HDA Intel PCH, ALC887-VD Analog" and "HDA Intel PCH, ALC887-VD Alt Analog". 

visuals are detecting sound regardless if they are plugged in or if music is playing at all on "HDA Intel PCH, ALC887-VD Analog" 

However on "HDA Intel PCH, ALC887-VD Alt Analog" its always flat and non responsive. 

I thought well may be there is something from the aux cable, changed it no change to either cards. 

Next thing I thought was may be its just because I am using the wrong output on deadbeef. (so I cycled through the various outputs and found the output labeled "HDA Intel PCH, ALC887-VD Analog" but after restarting the application it didn't seem to do much good)

Here is an example video. ( [https://www.youtube.com/watch?v=qoiGwbtIppk](https://www.youtube.com/watch?v=qoiGwbtIppk) )On the left is the binary running as root (still) and on the right is the compiled binary. The audio starts with pulse audio, then silence while I switch to ALSA to "HDA Intel PCH, ALC887-VD Analog" (default output device). The one on the right as expected stops working because its compiled with pulse in mind not alsa but the one on the left just keeps on doing its thing. 

I read on the steam community page that some guy just put in an audio source to the mic and I also tried that to no effect also. 

I'm going to try and restart and see if that does anything. IDK it always saves me in my line of work.

**Comment by kblaschke** [comment] 2021-06-09 21:15
There's also an issue with SDL2 and Pulseaudio: SDL2 filters out all "monitor" devices - these are the virtual audio devices that capture audio output to be used as an input in another application. Currently, the SDL2-based application can only record audio from real input devices like microphones or line-in on Linux. There's already [a bug report in the SDL repo](https://github.com/libsdl-org/SDL/issues/2917) for this.

**Comment by icculus** [comment] 2021-07-27 17:16
> There's already a bug report in the SDL repo for this.

We just fixed this issue in SDL, which will be in the 2.0.16 release, that we're working on wrapping up right now. If you get a chance, please test the latest in revision control and make sure it meets your needs!

**Closed** 2021-07-28 20:54 UTC
Labels: pulseaudio, sdl-frontend

**Comment by orien3243** [comment] 2021-08-01 22:20
Awesome-sauce it works. thanks a billion to the team that got this.
:)
